function Home() {
  return (
    <div>
      <p>
        PROPOSITO: ATINGIR O PROXIMO NIVEL E ALCANÇAR O QUE QUER VERDADEIRAMENTE
        DA VIDA E REPETIR O CICLO
      </p>
      <p>
        PERFIL DO USUARIO: PESSOAS BRUTALMENTE HONESTAS COM SI MESMAS DISPOSTAS
        A ENCARAR A SI MESMAS E MELHORAR
      </p>
      <p>
        1 feito : UM APP QUE AJUDE AS PESSOAS E A MIM A EVOLUIR ALNCAÇAR SEUS
        OBJETIVOS E A SER HONESTO COM SI MESMO E ENTENDER O QUE PRECISO FAZER E
        MUDAR PARA ALCANÇAR O QUE QUERO VERDADEIRAMENTE <br />
        ATRAVÉS DE DETERMINAR O QUE QUER DA VIDA E DESCOBRIR O PORQUÊ DE AGIR
        ,VISUALIZAÇÃO DE PROGRESSO, PLANEJAMENTO ESTRATEGICO DE METAS E
        SISTEMAS/ROTINAS, <br />
        ANTECIPANDO BARREIRAS E PREVENINDO-AS, CONSTRUIR UM MINDSET DE
        CRESCIMENTO E SUPERAÇÃO E SUBSTITUIR AS CRENÇAS NEGATIVAS
      </p>
      <p>
        2 protegido : A CHAMA DO CORAÇÃO DEVE PERMANECER ACESA E A HONESTIDADE E
        VERDADE COM SI MESMA DEVE SER MANTIDA
      </p>
      <p>3 repetido : AUTO REFLEXÃO PLANEJAMENTO AÇÃO E AUTO SUPERAÇÃO</p>
    </div>
  );
}
function teste(params) {
  console.log("olá");
}
export default Home;
